# Generated by Django 3.2.2 on 2021-05-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_pseudo', models.CharField(max_length=100, unique=True)),
                ('album_titre', models.CharField(max_length=100)),
                ('album_type', models.CharField(choices=[(1, 'VACCANCE'), (2, 'VOYAGE'), (3, 'BALADE'), (4, 'NATURE'), (5, 'FUN')], default='Nature', max_length=100)),
                ('album_photo', models.ImageField(blank=True, null=True, upload_to='statics/imagealbums')),
                ('album_label', models.TextField(max_length=200)),
                ('album_available', models.BooleanField(default=True)),
                ('album_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['album_pseudo'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pseudo', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_tel', models.IntegerField(unique=True)),
                ('user_phone', models.ImageField(blank=True, null=True, upload_to='statics/imageprofiles')),
                ('user_passe', models.CharField(max_length=100)),
                ('user_comment', models.TextField(max_length=100)),
                ('user_is_active', models.BooleanField(default=True)),
                ('user_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='statics/images')),
                ('photo_type', models.CharField(choices=[(1, 'VACCANCE'), (2, 'VOYAGE'), (3, 'BALADE'), (6, 'NATURE'), (7, 'FUN')], default='Nature', max_length=100)),
                ('photo_label', models.CharField(max_length=200)),
                ('photo_coord', models.IntegerField(blank=True, null=True)),
                ('photo_date', models.DateTimeField(auto_now_add=True)),
                ('album_pseudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millephoto.album')),
                ('user_pseudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millephoto.users')),
            ],
            options={
                'ordering': ['photo_label'],
            },
        ),
    ]
