# Generated by Django 3.2.2 on 2021-05-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_pseudo', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('album_titre', models.CharField(max_length=200)),
                ('album_label', models.TextField(max_length=100)),
                ('album_picture', models.URLField()),
                ('album_type', models.CharField(choices=[(1, 'VACCANCE'), (2, 'VOYAGE'), (3, 'BALADE'), (4, 'NATURE'), (5, 'FUN')], max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('album_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['album_pseudo', '-album_date'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('pseudo_user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email_user', models.EmailField(max_length=254)),
                ('tel_user', models.IntegerField()),
                ('date_user', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_taille', models.ImageField(height_field=40, upload_to='images/', width_field=50)),
                ('photo_type', models.CharField(choices=[(1, 'VACCANCE'), (2, 'VOYAGE'), (3, 'BALADE'), (6, 'NATURE'), (7, 'FUN')], max_length=100)),
                ('photo_comment', models.TextField(max_length=200)),
                ('photo_coord', models.IntegerField()),
                ('photo_date', models.DateTimeField(auto_now_add=True)),
                ('album_pseudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millephoto.album')),
            ],
            options={
                'ordering': ['album_pseudo', '-photo_date'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='pseudo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millephoto.users'),
        ),
    ]
